/**
 * Structured Feedback Schema v1.0
 * 
 * This schema defines the complete feedback structure generated by the LLM
 * with evidence-based scoring, timestamps, and study plan recommendations.
 */

// ============================================
// CORE TYPES
// ============================================

export type SupportedLanguage = 'en' | 'es' | 'pt' | 'zh' | 'hi' | 'ja' | 'ko' | 'de' | 'fr' | 'it';
export type Seniority = 'intern' | 'junior' | 'mid' | 'senior' | 'staff' | 'principal' | 'manager' | 'director' | 'vp' | 'c-level';
export type CompetencyKey = 
  | 'technical_knowledge'
  | 'problem_solving'
  | 'communication'
  | 'system_design'
  | 'behavioral'
  | 'leadership'
  | 'cultural_fit'
  | 'domain_expertise';

// ============================================
// SESSION METADATA
// ============================================

export interface SessionMetadata {
  sessionId: string;
  roleTitle: string;
  seniority: Seniority;
  language: SupportedLanguage;
  resumeUsed: boolean;
  interviewDuration: number; // seconds
  totalExchanges: number;
  interviewDate: string; // ISO 8601
  wasInterrupted: boolean;
  interruptionReason?: string;
}

// ============================================
// TRANSCRIPT EVIDENCE
// ============================================

export interface TranscriptEvidence {
  /** Timestamp in seconds from interview start */
  timestamp: number;
  /** Direct quote from candidate */
  quote: string;
  /** Speaker: 'candidate' or 'interviewer' */
  speaker: 'candidate' | 'interviewer';
  /** Context or question that prompted this response */
  context?: string;
}

// ============================================
// COMPETENCY SCORING
// ============================================

export interface CompetencyScore {
  /** Competency key for programmatic use */
  key: CompetencyKey;
  /** Localized display name */
  name: string;
  /** Score from 0-5 (0=not assessed, 1=poor, 5=excellent) */
  score: number;
  /** Confidence level 0-1 (how much evidence supports this score) */
  confidence: number;
  /** Brief explanation of the score */
  explanation: string;
  /** Evidence from transcript supporting this score */
  evidence: TranscriptEvidence[];
  /** Specific suggestions for improvement */
  improvementTips?: string[];
}

// ============================================
// STRENGTHS & IMPROVEMENTS
// ============================================

export interface StrengthItem {
  /** Concise title */
  title: string;
  /** Detailed description */
  description: string;
  /** Supporting evidence */
  evidence: TranscriptEvidence[];
  /** Related competency */
  competency: CompetencyKey;
}

export interface ImprovementItem {
  /** Concise title */
  title: string;
  /** Why this is important */
  why: string;
  /** How to practice/improve */
  howToImprove: string;
  /** Estimated time to address (e.g., "2-4 weeks") */
  timeToAddress: string;
  /** Supporting evidence */
  evidence: TranscriptEvidence[];
  /** Related competency */
  competency: CompetencyKey;
  /** Priority: 1=highest, 3=lowest */
  priority: 1 | 2 | 3;
}

// ============================================
// INTERVIEW HIGHLIGHTS
// ============================================

export interface InterviewHighlight {
  /** Type of highlight */
  type: 'strong_answer' | 'weak_answer' | 'key_moment';
  /** Timestamp in seconds */
  timestamp: number;
  /** The question asked */
  question: string;
  /** The candidate's response */
  response: string;
  /** Why this is notable */
  analysis: string;
  /** Related competency */
  competency: CompetencyKey;
}

// ============================================
// COMMUNICATION ANALYSIS
// ============================================

export interface CommunicationAnalysis {
  /** Overall communication score 0-5 */
  overallScore: number;
  /** Average words per minute */
  pace: {
    wpm: number;
    assessment: 'too_slow' | 'good' | 'too_fast';
    recommendation?: string;
  };
  /** Filler word analysis */
  fillerWords: {
    count: number;
    examples: string[];
    frequency: 'low' | 'moderate' | 'high';
    recommendation?: string;
  };
  /** Clarity assessment */
  clarity: {
    score: number; // 0-5
    assessment: string;
    examples?: TranscriptEvidence[];
  };
  /** Structure (STAR method usage, etc.) */
  structure: {
    score: number; // 0-5
    assessment: string;
    usedFrameworks: string[]; // e.g., ['STAR', 'CAR']
  };
  /** Technical vocabulary usage */
  technicalVocabulary: {
    score: number; // 0-5
    assessment: string;
    misusedTerms?: string[];
  };
}

// ============================================
// STUDY PLAN
// ============================================

export interface StudyPlanItem {
  /** Topic to study */
  topic: string;
  /** Why this is important for the role */
  rationale: string;
  /** Priority: 1=highest, 3=lowest */
  priority: 1 | 2 | 3;
  /** Estimated hours to study */
  estimatedHours: number;
  /** Suggested resources or exercises */
  exercises: string[];
  /** Related competency */
  competency: CompetencyKey;
}

// ============================================
// NEXT SESSION GOALS
// ============================================

export interface NextSessionGoal {
  /** Measurable goal description */
  goal: string;
  /** How to measure success */
  metric: string;
  /** Target value for the metric */
  target: string;
}

// ============================================
// DATA QUALITY INDICATORS
// ============================================

export interface DataQualityWarning {
  /** Warning code */
  code: 'incomplete_transcript' | 'short_interview' | 'missing_audio' | 'language_mismatch' | 'no_resume';
  /** Human-readable message */
  message: string;
  /** Severity level */
  severity: 'info' | 'warning' | 'error';
}

// ============================================
// MAIN FEEDBACK SCHEMA
// ============================================

export interface StructuredFeedback {
  /** Schema version for migration */
  schemaVersion: '1.0';
  
  /** Prompt version used to generate this feedback */
  promptVersion: string;
  
  /** LLM model used */
  model: string;
  
  /** Generation timestamp */
  generatedAt: string; // ISO 8601
  
  /** Session metadata */
  session: SessionMetadata;
  
  /** Overall score 0-100 */
  overallScore: number;
  
  /** Confidence interval for overall score */
  scoreConfidence?: {
    lower: number;
    upper: number;
  };
  
  /** Short executive summary (2-3 sentences) */
  executiveSummary: string;
  
  /** Competency breakdown */
  competencies: CompetencyScore[];
  
  /** Top strengths (3-5 items) */
  strengths: StrengthItem[];
  
  /** Areas for improvement (3-5 items) */
  improvements: ImprovementItem[];
  
  /** Interview highlights (best/worst moments) */
  highlights: InterviewHighlight[];
  
  /** Communication coaching data */
  communication: CommunicationAnalysis;
  
  /** Prioritized study plan */
  studyPlan: StudyPlanItem[];
  
  /** Next session goals (1-2 measurable goals) */
  nextSessionGoals: NextSessionGoal[];
  
  /** Data quality warnings */
  warnings: DataQualityWarning[];
}

// ============================================
// VALIDATION RESULT
// ============================================

export interface FeedbackValidationResult {
  isValid: boolean;
  errors: Array<{
    path: string;
    message: string;
    code: string;
  }>;
  warnings: Array<{
    path: string;
    message: string;
  }>;
}

// ============================================
// LEGACY COMPATIBILITY
// ============================================

/** Legacy feedback format for backward compatibility */
export interface LegacyFeedbackData {
  overall_rating: number;
  strengths: string[];
  areas_for_improvement: string[];
  technical_skills_rating: number;
  communication_skills_rating: number;
  problem_solving_rating: number;
  detailed_feedback: string;
  recommendations: string[];
  was_interrupted: boolean;
}

/**
 * Convert structured feedback to legacy format
 */
export function tolegacyFormat(feedback: StructuredFeedback): LegacyFeedbackData {
  return {
    overall_rating: Math.round(feedback.overallScore / 20), // 0-100 to 1-5
    strengths: feedback.strengths.map(s => s.description),
    areas_for_improvement: feedback.improvements.map(i => i.title),
    technical_skills_rating: feedback.competencies.find(c => c.key === 'technical_knowledge')?.score || 3,
    communication_skills_rating: feedback.competencies.find(c => c.key === 'communication')?.score || 3,
    problem_solving_rating: feedback.competencies.find(c => c.key === 'problem_solving')?.score || 3,
    detailed_feedback: feedback.executiveSummary,
    recommendations: feedback.improvements.map(i => i.howToImprove),
    was_interrupted: feedback.session.wasInterrupted
  };
}
